[build]
  command = "npm run build" # The build command for your project
  publish = "build/" # The directory to publish (where your built files reside)
  functions = "functions/" # The directory where your serverless functions reside (if applicable)
